// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjtmoajtxvqczsiexjyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqdG1vYWp0eHZxY3pzaWV4anlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTYwMjMsImV4cCI6MjA3MTI3MjAyM30.SmKvtosrOkCaQpj3FDe0efkuZSt3HF0YKCDjH679fQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});